import { Modal } from 'bootstrap';
import 'bootstrap';
const temaFixo = new URLSearchParams(location.search).get('tema');
function aplicarTema(preferencia) { const tema = preferencia === 'system' ? (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : preferencia; document.documentElement.dataset.bsTheme = ['light','dark'].includes(tema) ? tema : 'light'; }
function salvarTema(preferencia) { try { localStorage.setItem('frota-tema', preferencia); } catch (_) {} aplicarTema(preferencia); }
document.querySelectorAll('[data-theme-toggle]').forEach(botao => botao.addEventListener('click', () => salvarTema(document.documentElement.dataset.bsTheme === 'dark' ? 'light' : 'dark')));
document.querySelectorAll('[data-theme-select]').forEach(campo => { try { campo.value = localStorage.getItem('frota-tema') || 'system'; } catch (_) {} campo.addEventListener('change', () => salvarTema(campo.value)); });
matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => { try { if (!temaFixo && (localStorage.getItem('frota-tema') || 'system') === 'system') aplicarTema('system'); } catch (_) {} });
if (['light','dark'].includes(temaFixo)) { for (const link of document.querySelectorAll('a[href]')) { const destino = new URL(link.href, location.href); if (destino.origin === location.origin && !destino.hash) { destino.searchParams.set('tema', temaFixo); link.href = destino.href; } } }
for (const botao of document.querySelectorAll('[data-password-toggle]')) { botao.addEventListener('click', () => { const campo = document.getElementById(botao.dataset.passwordToggle); campo.type = campo.type === 'password' ? 'text' : 'password'; botao.textContent = campo.type === 'password' ? 'Mostrar' : 'Ocultar'; botao.setAttribute('aria-label', `${botao.textContent} senha`); }); }
let alterado = false, destinoPendente = null;
document.querySelectorAll('[data-dirty-form]').forEach(formulario => formulario.addEventListener('input', () => { alterado = true; }));
addEventListener('beforeunload', evento => { if (alterado) { evento.preventDefault(); evento.returnValue = ''; } });
document.addEventListener('click', evento => { const link = evento.target.closest('a[href]'); if (!alterado || !link || link.target === '_blank' || link.hasAttribute('download') || link.getAttribute('href').startsWith('#') || evento.ctrlKey || evento.metaKey) return; evento.preventDefault(); destinoPendente = () => location.assign(link.href); Modal.getOrCreateInstance(document.getElementById('discard-changes')).show(link); });
document.querySelector('[data-discard-confirm]')?.addEventListener('click', () => { alterado = false; destinoPendente?.(); });
for (const formulario of document.querySelectorAll('[data-review-form]')) {
 const etapas = [...formulario.querySelectorAll('.form-stage')]; let etapa = 0;
 function mostrarEtapa(indice) { etapa = indice; etapas.forEach((painel,i) => { painel.hidden = i !== indice; }); formulario.querySelectorAll('[data-step-label]').forEach((rotulo,i) => { rotulo.classList.toggle('active',i === indice); if (i === indice) rotulo.setAttribute('aria-current','step'); else rotulo.removeAttribute('aria-current'); }); formulario.querySelector('[data-step-prev]')?.toggleAttribute('hidden',indice === 0); formulario.querySelector('[data-step-next]')?.toggleAttribute('hidden',indice >= etapas.length-1); formulario.querySelector('[data-review-submit]')?.toggleAttribute('hidden',etapas.length > 0 && indice < etapas.length-1); }
 function validar(campos) { const partida=formulario.querySelector('[data-date-start]'),retorno=formulario.querySelector('[data-date-end]'); if (retorno) retorno.setCustomValidity(partida?.value && retorno.value && retorno.value <= partida.value ? 'O retorno deve ser posterior à partida.' : ''); for (const arquivo of formulario.querySelectorAll('input[type=file]')) arquivo.setCustomValidity([...arquivo.files].some(item => item.size > 10*1024*1024) ? 'Selecione arquivos de até 10 MB.' : ''); const invalido=campos.find(campo => !campo.checkValidity()); if (!invalido) return true; const painel=invalido.closest('.form-stage'); if (painel) mostrarEtapa(etapas.indexOf(painel)); invalido.reportValidity(); invalido.focus(); formulario.classList.add('was-validated'); return false; }
 formulario.querySelector('[data-step-next]')?.addEventListener('click',() => { if (validar([...etapas[etapa].querySelectorAll('input,select,textarea')])) { mostrarEtapa(etapa+1); etapas[etapa].querySelector('h2')?.focus(); } }); formulario.querySelector('[data-step-prev]')?.addEventListener('click',() => mostrarEtapa(Math.max(0,etapa-1)));
 formulario.addEventListener('submit',evento => { evento.preventDefault(); if (!validar([...formulario.querySelectorAll('input,select,textarea')])) return; const modal=document.getElementById(formulario.dataset.reviewForm),resumo=modal.querySelector('[data-review-summary]'); resumo.replaceChildren(); for (const campo of formulario.querySelectorAll('input:not([type=hidden]):not([type=password]),select,textarea')) { if (campo.type==='checkbox' && !campo.checked) continue; const rotulo=document.querySelector(`label[for="${CSS.escape(campo.id)}"]`)?.textContent.trim(); if (!rotulo) continue; const item=document.createElement('div'),titulo=document.createElement('dt'),valor=document.createElement('dd'); titulo.textContent=rotulo; valor.textContent=campo.type==='file' ? [...campo.files].map(arquivo=>arquivo.name).join(', ') || 'Nenhum arquivo' : campo.tagName==='SELECT' ? campo.selectedOptions[0]?.text || '—' : campo.value || '—'; item.append(titulo,valor); resumo.append(item); } Modal.getOrCreateInstance(modal).show(formulario.querySelector('[data-review-submit]')); }); if (etapas.length) mostrarEtapa(0);
}
for (const modal of document.querySelectorAll('.modal')) { let abertura; modal.addEventListener('show.bs.modal',evento=> { abertura=evento.relatedTarget || document.activeElement; }); modal.addEventListener('hidden.bs.modal',()=> { if (abertura?.isConnected) abertura.focus({preventScroll:true}); }); }
for (const formulario of document.querySelectorAll('form[data-loading-form]')) { formulario.addEventListener('submit',evento=> { if (!formulario.checkValidity()) return; if (alterado && formulario.hasAttribute('data-profile-switch')) { evento.preventDefault(); destinoPendente=()=> { alterado=false; formulario.requestSubmit(); }; Modal.getOrCreateInstance(document.getElementById('discard-changes')).show(evento.submitter); return; } formulario.setAttribute('aria-busy','true'); formulario.querySelector('[type=submit]')?.setAttribute('disabled',''); formulario.querySelector('.submit-loading')?.classList.remove('d-none'); }); }
addEventListener('pageshow',()=>document.querySelectorAll('form[aria-busy]').forEach(formulario=> { formulario.removeAttribute('aria-busy'); formulario.querySelector('[type=submit]')?.removeAttribute('disabled'); formulario.querySelector('.submit-loading')?.classList.add('d-none'); }));
for (const palco of document.querySelectorAll('[data-device-stage]')) { const iframe=palco.querySelector('iframe'),largura=Number(palco.dataset.deviceStage); const ajustar=()=> { const escala=palco.clientWidth/largura; iframe.style.width=`${largura}px`; iframe.style.height=`${palco.clientHeight/escala}px`; iframe.style.transform=`scale(${escala})`; }; new ResizeObserver(ajustar).observe(palco); ajustar(); }

for(const botao of document.querySelectorAll('[data-report-reload]')) botao.addEventListener('click',()=>{ for(const campo of botao.form.querySelectorAll('input[name="campos[]"]')) campo.disabled=true; });
for(const escolha of document.querySelectorAll('[data-checklist-result]')) escolha.addEventListener('change',()=>{const nota=escolha.closest('.row').querySelector('[data-checklist-note]');nota.required=escolha.value==='problema';});
for(const escolha of document.querySelectorAll('[data-fuel-type]')) escolha.addEventListener('change',()=>{const unidade=escolha.form.querySelector('[data-fuel-unit]');const correta={gasolina:'litro',etanol:'litro',diesel:'litro',gnv:'m3',eletricidade:'kwh'}[escolha.value];if(correta)unidade.value=correta;});
