<?php

return [
    'requests' => [
        'route' => 'solicitacoes',
        'title' => 'Solicitações', 'module' => 'solicitacoes', 'icon' => 'clipboard-list', 'url' => 'solicitacoes',
        'table' => 'vw_solicitacoes_atuais', 'owner' => 'r.solicitante_id', 'unit' => 'r.unidade_id', 'date' => 'r.saida_prevista',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'destino' => ['r.destino', 'Destino'], 'saida_prevista' => ['r.saida_prevista', 'Saída prevista', 'datetime'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['finalidade' => ['r.finalidade', 'Finalidade'], 'origem' => ['r.origem', 'Origem'], 'retorno_previsto' => ['r.retorno_previsto', 'Retorno previsto', 'datetime'], 'passageiros' => ['r.quantidade_passageiros', 'Passageiros'], 'solicitante' => ['r.solicitante', 'Solicitante'], 'unidade' => ['r.unidade', 'Unidade'], 'trajeto' => ['r.trajeto_planejado', 'Trajeto planejado']],
        'states' => ['rascunho', 'aguardando_analise', 'ajustes_solicitados', 'aprovada', 'negada', 'cancelada'],
        'actions' => ['edit' => ['Editar solicitação', 'editar'], 'send' => ['Revisar envio', 'enviar'], 'revision' => ['Abrir nova revisão', 'editar'], 'approve' => ['Aprovar solicitação', 'aprovar'], 'deny' => ['Negar solicitação', 'negar'], 'adjust' => ['Solicitar ajustes', 'solicitar_ajustes']],
        'create' => true,
    ],
    'trips' => [
        'title' => 'Viagens', 'module' => 'viagens', 'icon' => 'route', 'url' => 'viagens',
        'table' => 'vw_viagens_detalhadas', 'owner' => 'r.solicitante_id', 'unit' => 'r.unidade_id', 'date' => 'r.saida_prevista',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'veiculo' => ['r.veiculo', 'Veículo'], 'destino' => ['r.destino', 'Destino'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['placa' => ['r.placa', 'Placa'], 'motorista' => ['r.motorista', 'Motorista'], 'origem' => ['r.origem', 'Origem'], 'saida_prevista' => ['r.saida_prevista', 'Saída prevista', 'datetime'], 'retorno_previsto' => ['r.retorno_previsto', 'Retorno previsto', 'datetime'], 'saida_real' => ['r.saida_real', 'Saída registrada', 'datetime'], 'retorno_real' => ['r.retorno_real', 'Retorno registrado', 'datetime'], 'quilometragem_saida' => ['r.quilometragem_saida', 'Km de saída'], 'quilometragem_retorno' => ['r.quilometragem_retorno', 'Km de retorno'], 'distancia' => ['r.distancia_real_km', 'Distância percorrida']],
        'states' => ['programada', 'em_andamento', 'concluida', 'cancelada'],
        'actions' => ['departure' => ['Registrar saída', 'registrar_saida'], 'occurrence' => ['Registrar ocorrência', 'registrar_ocorrencia'], 'return' => ['Registrar retorno', 'registrar_retorno'], 'cancel' => ['Cancelar viagem', 'cancelar']],
    ],
    'fines' => [
        'title' => 'Multas', 'module' => 'multas', 'icon' => 'file-text', 'url' => 'financeiro/multas',
        'table' => 'vw_multas_detalhadas', 'owner' => 'r.responsavel_id', 'unit' => 'r.unidade_id', 'date' => 'r.ocorrido_em',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'placa' => ['r.placa', 'Placa'], 'valor' => ['r.valor', 'Valor', 'money', 'ver_valores'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['descricao' => ['r.descricao', 'Descrição'], 'numero_auto' => ['r.numero_auto', 'Número do auto'], 'orgao' => ['r.orgao_autuador', 'Órgão autuador'], 'ocorrido_em' => ['r.ocorrido_em', 'Ocorrência', 'datetime'], 'data_vencimento' => ['r.data_vencimento', 'Vencimento', 'date'], 'responsavel' => ['r.responsavel', 'Responsável']],
        'reportColumns' => ['veiculo' => ['r.veiculo', 'Veículo'], 'precisao_ocorrencia' => ['r.precisao_ocorrencia', 'Precisão da ocorrência']],
        'states' => ['sem_responsavel', 'aguardando_comprovante', 'em_conferencia', 'quitada', 'contestada', 'cancelada'],
        'actions' => ['edit' => ['Editar autuação', 'editar'], 'assign' => ['Atribuir responsável', 'atribuir_responsavel'], 'proof' => ['Enviar comprovante', 'enviar_comprovante'], 'verify' => ['Conferir comprovante', 'validar_pagamento'], 'correct' => ['Solicitar correção', 'validar_pagamento'], 'settle' => ['Confirmar quitação', 'validar_pagamento'], 'dispute' => ['Contestar multa', 'contestar'], 'cancel' => ['Cancelar multa', 'cancelar']], 'create' => true,
    ],
    'vehicles' => [
        'title' => 'Frota', 'module' => 'frota', 'icon' => 'car-front', 'url' => 'frota',
        'table' => 'vw_frota', 'owner' => null, 'unit' => 'r.unidade_id',
        'columns' => ['placa' => ['r.placa', 'Placa'], 'nome' => ['r.nome', 'Veículo'], 'categoria' => ['r.categoria', 'Categoria'], 'situacao' => ['r.situacao_operacional', 'Situação']],
        'details' => ['marca' => ['r.marca', 'Marca'], 'modelo' => ['r.modelo', 'Modelo'], 'ano' => ['r.ano_modelo', 'Ano'], 'capacidade' => ['r.capacidade', 'Capacidade'], 'quilometragem' => ['r.quilometragem_atual', 'Quilometragem'], 'unidade' => ['r.unidade', 'Unidade']],
        'states' => ['disponivel', 'em_viagem', 'manutencao', 'indisponivel', 'inativo', 'baixado'],
        'actions' => ['edit' => ['Editar veículo', 'editar'], 'block' => ['Bloquear período', 'gerenciar'], 'release' => ['Liberar bloqueio manual', 'gerenciar']], 'create' => true,
    ],
    'monitoring' => [
        'title' => 'Monitoramento', 'module' => 'rastreamento', 'icon' => 'map-pinned', 'url' => 'monitoramento',
        'table' => 'vw_monitoramento', 'id' => 'r.veiculo_id', 'owner' => null, 'unit' => 'r.unidade_id', 'date' => 'r.capturado_em',
        'columns' => ['placa' => ['r.placa', 'Placa'], 'nome' => ['r.nome', 'Veículo'], 'situacao' => ['r.situacao_comunicacao', 'Comunicação']],
        'details' => ['capturado_em' => ['r.capturado_em', 'Última posição', 'datetime', 'ver_localizacao'], 'latitude' => ['r.latitude', 'Latitude', 'text', 'ver_localizacao'], 'longitude' => ['r.longitude', 'Longitude', 'text', 'ver_localizacao'], 'velocidade' => ['r.velocidade_kmh', 'Velocidade (km/h)', 'text', 'ver_localizacao'], 'provedor' => ['r.provedor', 'Provedor']],
        'reportColumns' => ['fonte' => ['r.fonte', 'Fonte']],
        'states' => ['transmitindo', 'sem_comunicacao', 'sem_rastreador', 'rastreador_inativo'],
        'actions' => [],
    ],
    'expenses' => [
        'title' => 'Despesas', 'module' => 'despesas', 'icon' => 'file-text', 'url' => 'financeiro/despesas', 'table' => 'vw_despesas_detalhadas', 'owner' => 'r.criado_por', 'unit' => 'r.unidade_id', 'date' => 'r.data_despesa', 'dateOnly' => true,
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'veiculo' => ['r.veiculo', 'Veículo'], 'valor' => ['r.valor', 'Valor', 'money', 'ver_valores'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['data_despesa' => ['r.data_despesa', 'Data da despesa', 'date'], 'categoria' => ['r.categoria', 'Categoria'], 'descricao' => ['r.descricao', 'Descrição'], 'fornecedor' => ['r.fornecedor', 'Fornecedor'], 'numero_documento' => ['r.numero_documento', 'Documento'], 'valor_pago' => ['r.valor_pago', 'Pagamento confirmado', 'money', 'ver_valores'], 'pago_em' => ['r.pago_em', 'Data de pagamento', 'datetime']],
        'states' => ['registrada', 'em_conferencia', 'aprovada', 'paga', 'cancelada'], 'actions' => ['edit' => ['Editar despesa', 'editar'], 'submit' => ['Enviar para conferência', 'editar'], 'verify' => ['Conferir despesa', 'aprovar'], 'pay' => ['Confirmar pagamento', 'validar_pagamento'], 'cancel' => ['Cancelar despesa', 'cancelar']], 'create' => true,
    ],
    'fuel' => [
        'title' => 'Abastecimentos', 'module' => 'despesas', 'icon' => 'car-front', 'url' => 'financeiro/abastecimentos', 'table' => 'despesas', 'owner' => 'r.criado_por', 'unit' => 'r.unidade_id', 'date' => 'r.data_despesa', 'dateOnly' => true,
        'joins' => [['abastecimentos as f', 'f.despesa_id', 'r.id'], ['veiculos as v', 'v.id', 'r.veiculo_id']], 'required' => 'f.despesa_id',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'placa' => ['v.placa', 'Placa'], 'quantidade' => ['f.quantidade', 'Quantidade'], 'valor' => ['r.valor', 'Valor', 'money', 'ver_valores'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['combustivel' => ['f.combustivel', 'Combustível'], 'unidade_medida' => ['f.unidade_medida', 'Unidade de medida'], 'preco_unitario' => ['f.preco_unitario', 'Preço unitário', 'money', 'ver_valores'], 'quilometragem' => ['f.quilometragem', 'Quilometragem'], 'data_despesa' => ['r.data_despesa', 'Data', 'date']],
        'states' => [], 'actions' => ['edit' => ['Editar abastecimento', 'editar']], 'create' => true,
    ],
    'maintenance' => [
        'title' => 'Manutenção', 'module' => 'despesas', 'icon' => 'car-front', 'url' => 'financeiro/manutencoes', 'table' => 'manutencoes', 'owner' => 'r.criado_por', 'unit' => 'v.unidade_id', 'date' => 'r.inicio_previsto',
        'joins' => [['veiculos as v', 'v.id', 'r.veiculo_id'], ['despesas as d', 'd.id', 'r.despesa_id']],
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'placa' => ['v.placa', 'Placa'], 'tipo' => ['r.tipo', 'Tipo'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['descricao' => ['r.descricao', 'Descrição'], 'inicio_previsto' => ['r.inicio_previsto', 'Início previsto', 'datetime'], 'fim_previsto' => ['r.fim_previsto', 'Fim previsto', 'datetime'], 'quilometragem' => ['r.quilometragem', 'Quilometragem'], 'valor' => ['d.valor', 'Despesa vinculada', 'money', 'ver_valores']],
        'states' => ['planejada', 'em_execucao', 'concluida', 'cancelada'], 'actions' => ['edit' => ['Editar manutenção', 'editar'], 'start' => ['Iniciar manutenção', 'editar'], 'complete' => ['Concluir manutenção', 'editar'], 'cancel' => ['Cancelar manutenção', 'cancelar']], 'create' => true,
    ],
    'users' => [
        'title' => 'Usuários', 'module' => 'usuarios', 'icon' => 'home', 'url' => 'administracao/usuarios', 'table' => 'usuarios', 'owner' => 'r.id', 'unit' => 'r.unidade_id', 'date' => 'r.criado_em',
        'joins' => [['unidades as u', 'u.id', 'r.unidade_id']],
        'columns' => ['identificador' => ['r.identificador', 'Identificador'], 'nome' => ['r.nome', 'Nome'], 'unidade' => ['u.nome', 'Unidade'], 'situacao' => ['r.ativo', 'Situação', 'bool']],
        'details' => ['email' => ['r.email', 'E-mail'], 'telefone' => ['r.telefone', 'Telefone'], 'criado_em' => ['r.criado_em', 'Cadastro', 'datetime']],
        'reportColumns' => ['ativo' => ['r.ativo', 'Situação', 'bool']],
        'states' => ['0', '1'], 'stateLabels' => ['0' => 'Inativo', '1' => 'Ativo'], 'actions' => ['edit' => ['Editar usuário', 'editar'], 'links' => ['Revisar vínculos', 'gerenciar']], 'create' => true,
    ],
    'roles' => [
        'title' => 'Perfis e permissões', 'module' => 'perfis', 'icon' => 'clipboard-list', 'url' => 'administracao/perfis', 'table' => 'perfis', 'owner' => 'r.criado_por', 'unit' => null,
        'columns' => ['codigo' => ['r.codigo', 'Código'], 'nome' => ['r.nome', 'Perfil'], 'situacao' => ['r.ativo', 'Situação', 'bool']],
        'details' => ['descricao' => ['r.descricao', 'Descrição']],
        'reportColumns' => ['ativo' => ['r.ativo', 'Situação', 'bool']],
        'states' => ['0', '1'], 'stateLabels' => ['0' => 'Inativo', '1' => 'Ativo'], 'actions' => ['edit' => ['Editar perfil', 'editar'], 'duplicate' => ['Duplicar perfil', 'criar']], 'create' => true,
    ],
    'technical-routes' => [
        'title' => 'Rotas técnicas', 'module' => 'rotas', 'icon' => 'route', 'url' => 'administracao/rotas', 'table' => 'rotas_sistema', 'owner' => 'r.criado_por', 'unit' => null,
        'columns' => ['nome' => ['r.nome', 'Nome'], 'caminho' => ['r.caminho', 'Caminho'], 'metodo' => ['r.metodo_http', 'Método'], 'situacao' => ['r.ativa', 'Situação', 'bool']],
        'details' => ['chave' => ['r.chave', 'Chave'], 'modulo' => ['r.modulo_codigo', 'Módulo'], 'descricao' => ['r.descricao', 'Descrição'], 'implementada' => ['r.implementada', 'Implementação', 'bool'], 'protegida' => ['r.protegida', 'Proteção', 'bool']],
        'reportColumns' => ['ativa' => ['r.ativa', 'Situação', 'bool']],
        'states' => ['0', '1'], 'stateLabels' => ['0' => 'Desativada', '1' => 'Ativa'], 'actions' => ['edit' => ['Editar metadados', 'editar']], 'create' => true,
    ],
    'audit' => [
        'title' => 'Auditoria', 'module' => 'auditoria', 'icon' => 'history', 'url' => 'administracao/auditoria', 'table' => 'auditoria', 'owner' => 'r.ator_usuario_id', 'unit' => 'u.unidade_id', 'date' => 'r.criado_em',
        'joins' => [['usuarios as u', 'u.id', 'r.ator_usuario_id']],
        'columns' => ['evento' => ['r.evento', 'Evento'], 'ator' => ['r.ator_nome_snapshot', 'Ator'], 'entidade' => ['r.entidade', 'Entidade'], 'criado_em' => ['r.criado_em', 'Data', 'datetime']],
        'details' => ['perfil' => ['r.perfil_nome_snapshot', 'Perfil do ator'], 'entidade_id' => ['r.entidade_id', 'Identificador do registro']],
        'states' => [], 'actions' => [],
    ],
    'tickets' => [
        'title' => 'Chamados', 'module' => 'chamados', 'icon' => 'life-buoy', 'url' => 'chamados', 'table' => 'chamados', 'owner' => 'r.solicitante_id', 'unit' => 'r.unidade_id', 'date' => 'r.criado_em',
        'joins' => [['categorias_chamado as c', 'c.id', 'r.categoria_id']],
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'assunto' => ['r.assunto', 'Assunto'], 'categoria' => ['c.nome', 'Categoria'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['descricao' => ['r.descricao', 'Descrição'], 'criado_em' => ['r.criado_em', 'Abertura', 'datetime']],
        'states' => ['aberto', 'em_atendimento', 'aguardando_solicitante', 'resolvido'], 'actions' => ['respond' => ['Responder chamado', 'responder'], 'assign' => ['Atribuir atendimento', 'atender'], 'resolve' => ['Resolver chamado', 'resolver']], 'create' => true,
    ],
];
