<?php

return [
    'requests' => [
        'title' => 'Solicitações', 'module' => 'solicitacoes', 'icon' => 'clipboard-list', 'url' => 'solicitacoes',
        'table' => 'vw_solicitacoes_atuais', 'owner' => 'r.solicitante_id', 'unit' => 'r.unidade_id', 'date' => 'r.saida_prevista',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'destino' => ['r.destino', 'Destino'], 'saida_prevista' => ['r.saida_prevista', 'Saída prevista', 'datetime'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['finalidade' => ['r.finalidade', 'Finalidade'], 'origem' => ['r.origem', 'Origem'], 'retorno_previsto' => ['r.retorno_previsto', 'Retorno previsto', 'datetime'], 'passageiros' => ['r.quantidade_passageiros', 'Passageiros'], 'solicitante' => ['r.solicitante', 'Solicitante'], 'unidade' => ['r.unidade', 'Unidade'], 'trajeto' => ['r.trajeto_planejado', 'Trajeto planejado']],
        'states' => ['rascunho', 'aguardando_analise', 'ajustes_solicitados', 'aprovada', 'negada', 'cancelada'],
        'actions' => ['edit' => ['Editar solicitação', 'editar'], 'send' => ['Revisar envio', 'enviar'], 'approve' => ['Aprovar solicitação', 'aprovar'], 'deny' => ['Negar solicitação', 'negar'], 'adjust' => ['Solicitar ajustes', 'solicitar_ajustes'], 'cancel' => ['Cancelar solicitação', 'cancelar']],
        'create' => true,
    ],
    'trips' => [
        'title' => 'Viagens', 'module' => 'viagens', 'icon' => 'route', 'url' => 'viagens',
        'table' => 'vw_viagens_detalhadas', 'owner' => 'r.solicitante_id', 'unit' => 'r.unidade_id', 'date' => 'r.saida_prevista',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'veiculo' => ['r.veiculo', 'Veículo'], 'destino' => ['r.destino', 'Destino'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['placa' => ['r.placa', 'Placa'], 'motorista' => ['r.motorista', 'Motorista'], 'origem' => ['r.origem', 'Origem'], 'saida_prevista' => ['r.saida_prevista', 'Saída prevista', 'datetime'], 'retorno_previsto' => ['r.retorno_previsto', 'Retorno previsto', 'datetime'], 'saida_real' => ['r.saida_real', 'Saída registrada', 'datetime'], 'retorno_real' => ['r.retorno_real', 'Retorno registrado', 'datetime'], 'quilometragem_saida' => ['r.quilometragem_saida', 'Km de saída'], 'quilometragem_retorno' => ['r.quilometragem_retorno', 'Km de retorno'], 'distancia' => ['r.distancia_real_km', 'Distância percorrida']],
        'states' => ['programada', 'em_andamento', 'concluida', 'cancelada'],
        'actions' => ['departure' => ['Registrar saída', 'registrar_saida'], 'occurrence' => ['Registrar ocorrência', 'registrar_ocorrencia'], 'return' => ['Registrar retorno', 'registrar_retorno'], 'cancel' => ['Cancelar viagem', 'cancelar']],
    ],
    'fines' => [
        'title' => 'Multas', 'module' => 'multas', 'icon' => 'file-text', 'url' => 'multas',
        'table' => 'vw_multas_detalhadas', 'owner' => 'r.responsavel_id', 'unit' => 'r.unidade_id', 'date' => 'r.ocorrido_em',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'placa' => ['r.placa', 'Placa'], 'valor' => ['r.valor', 'Valor', 'money', 'ver_valores'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['descricao' => ['r.descricao', 'Descrição'], 'numero_auto' => ['r.numero_auto', 'Número do auto'], 'orgao' => ['r.orgao_autuador', 'Órgão autuador'], 'ocorrido_em' => ['r.ocorrido_em', 'Ocorrência', 'datetime'], 'data_vencimento' => ['r.data_vencimento', 'Vencimento', 'date'], 'responsavel' => ['r.responsavel', 'Responsável']],
        'states' => ['sem_responsavel', 'aguardando_comprovante', 'em_conferencia', 'quitada', 'contestada', 'cancelada'],
        'actions' => ['assign' => ['Atribuir responsável', 'atribuir_responsavel'], 'proof' => ['Enviar comprovante', 'enviar_comprovante'], 'verify' => ['Conferir comprovante', 'validar_pagamento'], 'correct' => ['Solicitar correção', 'validar_pagamento'], 'settle' => ['Confirmar quitação', 'validar_pagamento'], 'dispute' => ['Contestar multa', 'contestar'], 'cancel' => ['Cancelar multa', 'cancelar']], 'create' => true,
    ],
    'vehicles' => [
        'title' => 'Frota', 'module' => 'frota', 'icon' => 'car-front', 'url' => 'frota',
        'table' => 'vw_frota', 'owner' => null, 'unit' => 'r.unidade_id',
        'columns' => ['placa' => ['r.placa', 'Placa'], 'nome' => ['r.nome', 'Veículo'], 'categoria' => ['r.categoria', 'Categoria'], 'situacao' => ['r.situacao_operacional', 'Situação']],
        'details' => ['marca' => ['r.marca', 'Marca'], 'modelo' => ['r.modelo', 'Modelo'], 'ano' => ['r.ano_modelo', 'Ano'], 'capacidade' => ['r.capacidade', 'Capacidade'], 'quilometragem' => ['r.quilometragem_atual', 'Quilometragem'], 'unidade' => ['r.unidade', 'Unidade']],
        'states' => ['disponivel', 'em_viagem', 'manutencao', 'indisponivel', 'baixado'],
        'actions' => ['edit' => ['Editar veículo', 'editar']], 'create' => true,
    ],
    'monitoring' => [
        'title' => 'Monitoramento', 'module' => 'rastreamento', 'icon' => 'map-pinned', 'url' => 'monitoramento',
        'table' => 'vw_monitoramento', 'id' => 'r.veiculo_id', 'owner' => null, 'unit' => 'r.unidade_id',
        'columns' => ['placa' => ['r.placa', 'Placa'], 'nome' => ['r.nome', 'Veículo'], 'situacao' => ['r.situacao_comunicacao', 'Comunicação']],
        'details' => ['capturado_em' => ['r.capturado_em', 'Última posição', 'datetime', 'ver_localizacao'], 'latitude' => ['r.latitude', 'Latitude', 'text', 'ver_localizacao'], 'longitude' => ['r.longitude', 'Longitude', 'text', 'ver_localizacao'], 'velocidade' => ['r.velocidade_kmh', 'Velocidade (km/h)', 'text', 'ver_localizacao'], 'provedor' => ['r.provedor', 'Provedor']],
        'states' => ['transmitindo', 'sem_comunicacao', 'sem_rastreador', 'rastreador_inativo'],
        'actions' => [],
    ],
    'expenses' => [
        'title' => 'Despesas', 'module' => 'despesas', 'icon' => 'file-text', 'url' => 'despesas', 'table' => 'vw_despesas_detalhadas', 'owner' => 'r.criado_por', 'unit' => 'r.unidade_id', 'date' => 'r.data_despesa', 'dateOnly' => true,
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'veiculo' => ['r.veiculo', 'Veículo'], 'valor' => ['r.valor', 'Valor', 'money', 'ver_valores'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['data_despesa' => ['r.data_despesa', 'Data da despesa', 'date'], 'categoria' => ['r.categoria', 'Categoria'], 'descricao' => ['r.descricao', 'Descrição'], 'fornecedor' => ['r.fornecedor', 'Fornecedor'], 'numero_documento' => ['r.numero_documento', 'Documento'], 'valor_pago' => ['r.valor_pago', 'Pagamento confirmado', 'money', 'ver_valores'], 'pago_em' => ['r.pago_em', 'Data de pagamento', 'datetime']],
        'states' => ['registrada', 'em_conferencia', 'aprovada', 'paga', 'cancelada'], 'actions' => ['edit' => ['Editar despesa', 'editar'], 'verify' => ['Conferir despesa', 'validar_pagamento'], 'cancel' => ['Cancelar despesa', 'cancelar']], 'create' => true,
    ],
    'fuel' => [
        'title' => 'Abastecimentos', 'module' => 'despesas', 'icon' => 'car-front', 'url' => 'abastecimentos', 'table' => 'despesas', 'owner' => 'r.criado_por', 'unit' => 'r.unidade_id', 'date' => 'r.data_despesa', 'dateOnly' => true,
        'joins' => [['abastecimentos as f', 'f.despesa_id', 'r.id'], ['veiculos as v', 'v.id', 'r.veiculo_id']], 'required' => 'f.despesa_id',
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'placa' => ['v.placa', 'Placa'], 'quantidade' => ['f.quantidade', 'Quantidade'], 'valor' => ['r.valor', 'Valor', 'money', 'ver_valores']],
        'details' => ['combustivel' => ['f.combustivel', 'Combustível'], 'unidade_medida' => ['f.unidade_medida', 'Unidade de medida'], 'preco_unitario' => ['f.preco_unitario', 'Preço unitário', 'money', 'ver_valores'], 'quilometragem' => ['f.quilometragem', 'Quilometragem'], 'data_despesa' => ['r.data_despesa', 'Data', 'date']],
        'states' => [], 'actions' => ['edit' => ['Editar abastecimento', 'editar']], 'create' => true,
    ],
    'maintenance' => [
        'title' => 'Manutenção', 'module' => 'despesas', 'icon' => 'car-front', 'url' => 'manutencoes', 'table' => 'manutencoes', 'owner' => 'r.criado_por', 'unit' => 'v.unidade_id', 'date' => 'r.inicio_previsto',
        'joins' => [['veiculos as v', 'v.id', 'r.veiculo_id'], ['despesas as d', 'd.id', 'r.despesa_id']],
        'columns' => ['protocolo' => ['r.protocolo', 'Protocolo'], 'placa' => ['v.placa', 'Placa'], 'tipo' => ['r.tipo', 'Tipo'], 'situacao' => ['r.situacao', 'Situação']],
        'details' => ['descricao' => ['r.descricao', 'Descrição'], 'inicio_previsto' => ['r.inicio_previsto', 'Início previsto', 'datetime'], 'fim_previsto' => ['r.fim_previsto', 'Fim previsto', 'datetime'], 'quilometragem' => ['r.quilometragem', 'Quilometragem'], 'valor' => ['d.valor', 'Despesa vinculada', 'money', 'ver_valores']],
        'states' => ['planejada', 'em_execucao', 'concluida', 'cancelada'], 'actions' => ['edit' => ['Editar manutenção', 'editar'], 'cancel' => ['Cancelar manutenção', 'cancelar']], 'create' => true,
    ],
];
