<?php
require '/var/www/html/vendor/autoload.php';$app=require '/var/www/html/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;
if(DB::connection()->getDatabaseName()!=='frota_pf_local'||config('database.connections.mysql.host')!=='mysql-local')exit(1);
$counts=[];foreach(DB::select('SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_TYPE="BASE TABLE" ORDER BY TABLE_NAME') as $t)$counts[$t->TABLE_NAME]=DB::table($t->TABLE_NAME)->count();
$keys=DB::select('SELECT TABLE_NAME,CONSTRAINT_NAME,COLUMN_NAME,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL ORDER BY TABLE_NAME,CONSTRAINT_NAME,ORDINAL_POSITION');$groups=[];foreach($keys as $k)$groups[$k->TABLE_NAME.'.'.$k->CONSTRAINT_NAME][]=$k;
$orphans=0;foreach($groups as $parts){$join=[];$nonnull=[];foreach($parts as $k){$join[]='c.`'.$k->COLUMN_NAME.'`=p.`'.$k->REFERENCED_COLUMN_NAME.'`';$nonnull[]='c.`'.$k->COLUMN_NAME.'` IS NOT NULL';}$orphans+=(int)DB::selectOne('SELECT COUNT(*) n FROM `'.$parts[0]->TABLE_NAME.'` c LEFT JOIN `'.$parts[0]->REFERENCED_TABLE_NAME.'` p ON '.implode(' AND ',$join).' WHERE '.implode(' AND ',$nonnull).' AND p.`'.$parts[0]->REFERENCED_COLUMN_NAME.'` IS NULL')->n;}
$files=0;foreach(DB::table('arquivos')->get() as $f){$bytes=Storage::disk('local')->get($f->chave_armazenamento);if(strlen($bytes)!=(int)$f->tamanho_bytes||hash('sha256',$bytes,true)!==$f->sha256)throw new RuntimeException('Arquivo inconsistente');$files++;}
$views=0;foreach(DB::select('SELECT TABLE_NAME FROM information_schema.VIEWS WHERE TABLE_SCHEMA=DATABASE()') as $v){DB::table($v->TABLE_NAME)->limit(1)->get();$views++;}
echo json_encode(['database'=>'frota_pf_local','tables'=>$counts,'fk_checked'=>count($groups),'orphans'=>$orphans,'files_checked'=>$files,'views_checked'=>$views],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);
